import { unlink } from 'node:fs/promises';
import { validateEquals } from 'typia';
import { Config } from '../util/type';
import { GetConfig, SaveConfig } from './config';
import { CreateDataFile } from './data';

export interface EntryRequest {
    kind: 'templates' | 'upstreams' | 'rules';
    index: number | null;
    value: Record<string, any>;
    contents?: Record<string, string>;
}

let saves: Promise<void> = Promise.resolve();
export function SaveEntry(body: EntryRequest) {
    const result = saves.then(() => SaveEntryNow(body));
    saves = result.then(() => undefined, () => undefined);
    return result;
}

async function SaveEntryNow(body: EntryRequest) {
    if (!['templates', 'upstreams', 'rules'].includes(body.kind)) throw new Error('invalid entry kind');
    const config = GetConfig();
    const entries = [...(config[body.kind] ?? [])];
    if (body.index !== null && (!Number.isInteger(body.index) || body.index < 0 || body.index >= entries.length)) throw new Error('invalid entry index');
    const existing: any = body.index === null ? undefined : entries[body.index];
    const value = { ...body.value };
    const contents = body.contents ?? {};
    const pending: { field: string; content: string; extension: 'yaml' | 'json' | 'txt' }[] = [];
    function file(field: string, extension: 'yaml' | 'json' | 'txt', previous?: string) {
        if (Object.hasOwn(contents, field)) {
            if (typeof contents[field] !== 'string') throw new Error('文件内容必须是文本');
            pending.push({ field, content: contents[field]!, extension });
            value[field] = '__pending__';
        } else if (previous) value[field] = previous;
        else throw new Error('请填写文件内容');
    }
    const fields = body.kind === 'templates' ? ['path'] : ['from'];
    if (Object.keys(contents).some(key => !fields.includes(key))) throw new Error('invalid file field');
    if (body.kind === 'templates') {
        file('path', 'yaml', existing?.path);
        if (entries.some((entry: any, index) => index !== body.index && entry.target === value.target)) throw new Error('只能配置一个 Clash 输出模板');
    } else {
        if (value.source === 'local') file('from', value.format === 'json' ? 'json' : value.format === 'node-list' ? 'txt' : 'yaml', existing?.source === 'local' ? existing.from : undefined);
        else if (Object.hasOwn(contents, 'from')) throw new Error('远程来源不接受本地文件内容');
    }
    if (body.index === null) entries.push(value as any);
    else entries[body.index] = value as any;
    const next = { ...config, [body.kind]: entries } as Config;
    const result = validateEquals<Config>(next);
    if (!result.success) throw new Error(JSON.stringify(result.errors));
    const created: string[] = [];
    try {
        for (const item of pending) {
            const path = await CreateDataFile(item.content, item.extension);
            created.push(path);
            value[item.field] = path;
        }
        return SaveConfig(next);
    } catch (error) {
        // Only remove files generated by this request; existing references stay intact.
        await Promise.all(created.map(path => unlink(path).catch(() => undefined)));
        throw error;
    }
}
